### ISSUE TITLE
Reference genome installation and wget

### ISSUE THREAD

**Issue by senkin** [AlexandrovLab/SigProfilerSimulator#1]
Hi @ebergstr, 

Thanks for the great tool! A couple of suggestions from me:

1. The argument `c("96")` of `contexts` variable in  the example `sigSim.SigProfilerSimulator` command in [Readme](https://github.com/AlexandrovLab/SigProfilerSimulator/blame/master/README.md#L36) throws an error in my environment: `  NameError: name 'c' is not defined`
**`contexts=["96"]`** works though, so I suggest changing example command to that.

2. If the reference genome is not downloaded, nothing seems to happen when `Chromosome proportion file does not exist. Creating now...` message appears. Manual download as per [SigProfilerMatrixGenerator Readme](https://github.com/AlexandrovLab/SigProfilerSimulator/blob/master/README.md) works, so perhaps it's worth mentioning it in SigProfilerSimulator readme, too.

3. When installing the reference genome, `The ensembl ftp site is not currently responding.` error appears even when WGET is not installed. Although this tool is mentioned in [Readme](https://github.com/AlexandrovLab/SigProfilerSimulator/blob/master/README.md) as a prerequisite, perhaps it's worth adding an exception [here](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/install.py#L414) to check if WGET is available.

Best,
Sergey

**Comment by ebergstr** [comment]
Hi Sergey,

Thank you for the useful feedback! These changes are addressed in SigProfilerMatrixGenerator v1.1.2 and SigProfilerSimulator v1.0.1.

1. This command in the README is now corrected.
2. The code should now exit once realizing that there are no chromosome reference files saved, thus preventing the chromosome proportion function from beginning. The exit message will direct the user to the matrixGenerator page for installation instructions. Similarly, I added a prerequisite note to install the desired reference genome following the matrixGenerator README.
3. The wget check was previously included in the install script, however, it was unintentionally removed. Thanks for pointing that out! We added the check back in.

Best,
Erik
