### ISSUE TITLE
Hard-coded chromosomes make it impossible to run code with "chr" prefix for chromosome IDs or "MT" chromosomes

### ISSUE THREAD

**Issue by cdupai-bbi** [AlexandrovLab/SigProfilerSimulator#7]
https://github.com/AlexandrovLab/SigProfilerSimulator/blob/ced39a81e38098fc9c42b90255e5f70144ac52aa/SigProfilerSimulator/SigProfilerSimulator.py#L162C1-L163C67

Because the chromosomes are hardcoded without the chr prefix, it is impossible to run SigProfilerSimulator on non-Ensembl GRCh38 genomes that have the "chr" prefix before the chromosome number. Additionally, there is no MT chromosome listed so the code also breaks on vcf files containing MT chromosomes.

**Comment by MousumyCSE** [comment]
Hi @cdupai-bbi,

Apologies for the late response!

I have run a vcf file with 'chr' prefix and chromosome 'MT', it works fine at my end. 
If you still have the same problem, our suggestion will be to remove 'chr' prefix and 'MT' chromosome before you run SigProfilerSimulator.

Thanks,
Mousumy

**Comment by MousumyCSE** [comment]
Hi @cdupai-bbi,

If you encounter any issues, please feel free to reopen the issue.

Thanks!
Mousumy
